version: "3"

# See https://github.com/plone/plone-backend/tree/6.0.x
# https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc
# https://github.com/mcuadros/ofelia

services:
  zeo:
    image: plone/plone-zeo:latest
    volumes:
      - ./data:/data
#   ports:
#     - "8100:8100"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.weekly-backup.schedule: "0 0 2 * * 0"
      ofelia.job-exec.weekly-backup.command: "/app/bin/repozo -B -f /app/var/filestorage/Data.fs -r /app/var/backup"

  frontend:
    image: tiberiuichim/vanabbe:1.36
    profiles: ["production"]
    # depends_on:
    # - plone
    #environment:
    #RAZZLE_INTERNAL_API_PATH: "http://plone:8080/Plone"

  plone:
    image: tiberiuichim/vanabbe-backend:6.0.0-3
    depends_on:
      - zeo
    environment:
      ZEO_ADDRESS: zeo:8100
      # ADDONS: "collective.volto.cookieconsent collective.volto.formsupport"
      DEVELOP: "/app/src/collective.previewimage -e /app/src/intk_vanabbe"
    volumes:
      - cache:/data
      - ./backend/src:/app/src
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.monthly-pack.schedule: "0 0 0 1 * *"
      ofelia.job-exec.monthly-pack.command: "/app/bin/zeopack -h zeo -p 8100 -d 3"
    #entrypoint: sh -c "tail -f /dev/null"
    healthcheck:
      disable: true

  # See https://github.com/mcuadros/ofelia
  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles: ["production"]

# nginx:
#   build: ./webserver/nginx
#   image: tiberiuichim/nginx
#   env_file:
#     - ./webserver.env
#   volumes:
#     - ./webserver/data/nginx_conf:/etc/nginx/sites
#     - ./webserver/data/letsencrypt_certs:/etc/letsencrypt
#     - ./webserver/data/certbot_acme_challenge:/var/www/certbot
#     - ./webserver/data/vhosts:/etc/nginx/vhosts
#     - ./webserver/data/html:/var/www/html
#   ports:
#     - "80:80"
#     - "443:443"
#   restart: unless-stopped
#   profiles: ["production"]

# certbot:
#   depends_on:
#     - nginx
#   build: ./webserver/certbot
#   image: tiberiuichim/certbot
#   env_file:
#     - ./webserver.env
#   volumes:
#     - ./webserver/data/letsencrypt_certs:/etc/letsencrypt
#     - ./webserver/data/certbot_acme_challenge:/var/www/certbot
#   profiles: ["production"]

# cron:
#   depends_on:
#     - certbot
#   build: ./webserver/cron
#   image: tiberiuichim/cron
#   environment:
#     COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     - ./:/workdir:ro
#   # needs direct access to current docker-compose project so that it can run `docker-compose` commands
#   restart: unless-stopped
#   profiles: ["production"]

volumes:
  cache: {}
